"""empty message

Revision ID: 10374fdf4e4a
Revises: 70990663ad40
Create Date: 2020-12-21 19:28:05.047339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10374fdf4e4a'
down_revision = '70990663ad40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expense', 'verified',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='verified::int')

    op.alter_column('incoming', 'verified',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='verified::int')
    op.execute('UPDATE expense SET verified = 2')
    op.execute('UPDATE incoming SET verified = 2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('incoming', 'verified',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               postgresql_using='verified::boolean')
    op.alter_column('expense', 'verified',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               postgresql_using='verified::boolean')
    op.execute('UPDATE expense SET verified = True')
    op.execute('UPDATE incoming SET verified = True')
    # ### end Alembic commands ###
