"""empty message

Revision ID: 19b4f4837ee4
Revises: 66abfcfd92ee
Create Date: 2020-10-16 20:22:13.015124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b4f4837ee4'
down_revision = '66abfcfd92ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liquids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prefix', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('balance', sa.Numeric(precision=2, asdecimal=False), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liquids')
    # ### end Alembic commands ###
