"""empty message

Revision ID: 39dcef6cced3
Revises: 19b4f4837ee4
Create Date: 2020-10-17 19:12:53.348520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dcef6cced3'
down_revision = '19b4f4837ee4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquids', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted')
    op.drop_column('liquids', 'deleted')
    # ### end Alembic commands ###
