"""empty message

Revision ID: 4a37cbc209c7
Revises: 39dcef6cced3
Create Date: 2020-10-17 20:57:17.848464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a37cbc209c7'
down_revision = '39dcef6cced3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('liquids', sa.Column('used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liquids', 'used')
    # ### end Alembic commands ###
