"""empty message

Revision ID: 66abfcfd92ee
Revises: d41030d80ddf
Create Date: 2020-10-16 20:21:28.500682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66abfcfd92ee'
down_revision = 'd41030d80ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'employee')
    # ### end Alembic commands ###
