"""empty message

Revision ID: 8ddc1e17bcea
Revises: f83467ee24dd
Create Date: 2020-12-28 17:06:10.931617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ddc1e17bcea'
down_revision = 'f83467ee24dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'title', nullable=False, new_column_name='model')
    op.add_column('vehicles', sa.Column('brand', sa.String(length=200), nullable=True))
    op.add_column('vehicles', sa.Column('government_number_letters', sa.String(length=2), nullable=True))
    op.add_column('vehicles', sa.Column('government_number_region', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('year_of_ussue', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'year_of_ussue')
    op.drop_column('vehicles', 'worker_id')
    op.drop_column('vehicles', 'model')
    op.drop_column('vehicles', 'government_number_region')
    op.drop_column('vehicles', 'government_number_letters')
    op.drop_column('vehicles', 'brand')
    # ### end Alembic commands ###
