"""empty message

Revision ID: ae7cc9135264
Revises: 6b53340e13dd
Create Date: 2021-08-26 10:52:22.716664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7cc9135264'
down_revision = '6b53340e13dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('purpose_who', sa.String(length=200), default=''))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expense', 'purpose_who')
    # ### end Alembic commands ###
