"""empty message

Revision ID: b20060e171fa
Revises: 407197847838
Create Date: 2020-12-14 17:27:29.259304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b20060e171fa'
down_revision = '407197847838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('verified', sa.Boolean(), nullable=True))
    op.add_column('incoming', sa.Column('verified', sa.Boolean(), nullable=True))

    op.execute('UPDATE expense SET verified = true')
    op.execute('UPDATE incoming SET verified = true')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incoming', 'verified')
    op.drop_column('expense', 'verified')
    # ### end Alembic commands ###
